### PR TITLE
fix(FE-655): applied the cohort filter to summary report column modal

### LINKED ISSUE #215: ENHANCEMENTS - list of enhancements suggested

### PR DESCRIPTION
**Pull request by quisranti-j**
## Description
Applied the cohort filter to summary report column modal implementing the new service to get student list

## Type of change

- [x] Bug fix
- [ ] Feature
- [x] Refactor
- [ ] Documentation Improvements
- [ ] Others:

## Checklist

- [x] Have the requirements been met?
- [x] Is the code easy to read?
- [x] Do unit tests pass?
- [x] Is the code formatted correctly?

## Angular Checklist

- [ ] Are components following the single responsibility principle?
- [ ] Is the routing configuration clean and well-organized?
- [ ] Are form validations implemented and working correctly?
- [ ] Are errors gracefully handled and logged?
- [ ] Is there a consistent approach to styling (CSS, SCSS, CSS-in-JS)?
- [ ] Is user input sanitized to prevent XSS attacks?
- [ ] Are all dependencies necessary and up-to-date?

## Design Checklist
- [ ] Most important content is be visible on all screen sizes
- [ ] Space is properly used on all screen sizes
- [ ] Texts are properly displayed on all sizes (lines around 40 em, no overflows)
- [ ] Design follows accesibility guidelines
- [ ] Only relative units are used (vw, vh, ems or %)
- [ ] Only modern layout techniques are used (flexbox and grid)
- [ ] Large touch targets on mobile (minumim tap size: 48px X 48px)

## Related Issues
[FE-655](https://github.com/JU-DEV-Bootcamps/ERAS-FE/issues/655)

### CODE REVIEW

**Review by MauroFonsecaJala — CHANGES_REQUESTED** [review]
Data seems to be retrieved properly. However, a runtime error ocurs when changing lastVersion: ExpressionChangedAfterItHasBeenCheckedError

File: src/app/modules/reports/components/summary-charts/risk-details/risk-details.component.ts [hunk 1]
```diff
@@ -20,6 +20,8 @@ import { ReportService } from '@core/services/api/report.service';
 import { BadgeRiskComponent } from '@shared/components/badge-risk-level/badge-risk-level.component';
 import { ListComponent } from '@shared/components/list/list.component';
 import { ModalStudentDetailComponent } from '@shared/components/modals/modal-student-detail/modal-student-detail.component';
+import { EvaluationDetailsService } from '@core/services/api/evaluation-details.service';
```
Comment (JoseLuisGuevara) [inline src/app/modules/reports/components/summary-charts/risk-details/risk-details.component.ts]: Hi Isra, just a small change here. 
Let's order this **imports**, move this service up where the services sections are.
Same with the model import down, move it to its right place.

**Review by JoseLuisGuevara — CHANGES_REQUESTED** [review]

**Review by mmoralesv — APPROVED** [review]

**Review by MauroFonsecaJala — APPROVED** [review]

**Review by JoseLuisGuevara — APPROVED** [review]
LGTM
